name: CI

# Run on pull request, when first opened, and when approved, don't allow until the approved unit test pass
on:
  push:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version:
          - "3.10"
          - "3.11"
    name: Test
    runs-on: ${{ matrix.os }}
    env:
      PYTHONPATH: "."

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          ls
          pwd
          pip install pipenv
          pipenv install --dev
          

      - name: Debug Environment
        run: |
          echo "TOGETHER_API_KEY exists: ${{ secrets.TOGETHER_API_KEY != '' }}"
          echo "OPENAI_API_KEY exists: ${{ secrets.OPENAI_API_KEY != '' }}"

      - name: Run tests
        run: |
          PIPENV_DOTENV_LOCATION=.env pipenv run pytest -v
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
          PYTHONPATH: "."
